Add 172b-exp2 card
llm-jp/model-cards pull request #13
Opened 2024-07-17 08:49 UTC by odashi

Settings is fixed according to the discussion on the model WG.

Important changes from v3:

* Use v3.1 corpus: fix whitespace issues on WARP
* Change initial learning rate from 1e-4 to 8e-5
* **Change Adam epsilon from 1e-5 to 1e-8**

Discussion:
https://docs.google.com/document/d/1AY_yhyBCWqpQTHvXKjk-m5BTXByedrDZzDOgjDw6GoQ/edit#heading=h.39oxz76vdp54

This PR also adds a row for final LR for each card.

2024-07-18 12:09 UTC, jnszk requested changes

2024-07-18 12:09 UTC, jnszk commented on models/geniac-172b-exp2.md
> +|Number of tokens|**FIXME**|
最終的なデータ量が確定したら ** FIXME **を修正する

geniac-13B-exp4 と同じ値になるはず

2024-07-18 12:09 UTC, jnszk commented on models/geniac-172b-exp2.md
> +|Total training steps|**FIXME**|
最終的なデータ量が確定したら ** FIXME **を修正する

Learning rate Decay stepsとTotal training stepsは同じ値とする

2024-07-19 06:20 UTC, jnszk submitted a review, later dismissed

2024-07-20 13:35 UTC, odashi commented on models/geniac-172b-exp2.md
> +|Total training steps|**FIXME**|
memo: total = warmup + decay なので2,000だけ差があります

2024-07-21 05:52 UTC, odashi commented
@jnszk もう一度approveお願いします

2024-07-26 09:36 UTC, jnszk approved these changes

2024-07-26 09:58 UTC, merged